### ISSUE TITLE
Error on step #8

### ISSUE THREAD

**Issue by jiangweiatgithub** [chrishokamp/handycat#6]
I use WSL and get the follow error:

root@ee4a310cb48f:/handycat# npm install
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.

> gifsicle@0.1.7 postinstall /handycat/node_modules/gifsicle
> node index.js

internal/validators.js:125
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at validateString (internal/validators.js:125:11)
    at Object.basename (path.js:1289:5)
    at /handycat/node_modules/download/index.js:35:43
    at each (/handycat/node_modules/each-async/each-async.js:63:4)
    at module.exports (/handycat/node_modules/download/index.js:33:5)
    at /handycat/node_modules/bin-wrapper/index.js:108:20
    at /handycat/node_modules/bin-wrapper/index.js:141:24
    at /handycat/node_modules/bin-check/index.js:30:20
    at /handycat/node_modules/executable/index.js:39:20
    at FSReqWrap.oncomplete (fs.js:153:21)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN karma-requirejs@0.2.6 requires a peer of requirejs@^2.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN handycat@0.0.0 No repository field.
npm WARN handycat@0.0.0 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gifsicle@0.1.7 postinstall: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gifsicle@0.1.7 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-10-10T06_20_14_999Z-debug.log

**Comment by chrishokamp** [comment]
hi I don't understand what you are trying to do, if you can explain I will try to help, but  note that this codebase is pretty old

**Comment by chrishokamp** [comment]
it looks like it's a dependency that you might be able to resolve by manually installing `requirejs@^2.1.0`
